name: rentak
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  bloc: ^8.1.2
  bloc_provider: ^1.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  email_validator: ^2.1.16
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: null
  meta: ^1.9.1
  retrofit: ^4.0.3
  searchfield: ^0.8.7
  shared_preferences: null
  table_calendar: ^3.0.9

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/villa.jpg
    - assets/images/villa2.jpg
    - assets/images/villa3.jpg
    - assets/images/villa4.jpeg

    - assets/images/user.png
